# CodeGate Example Configuration

# Network settings
port: 8989           # Port to listen on (1-65535)
host: "localhost"      # Host to bind to (use localhost for all interfaces)

# Logging configuration
log_level: "INFO"  # One of: ERROR, WARNING, INFO, DEBUG
log_format: "JSON"  # One of: JSON, TEXT

# Model configuration
model_base_path: "./codegate_volume/models"
embedding_model: "all-minilm-L6-v2-q5_k_m.gguf"

# Chat model configuration
chat_model_n_ctx: 32768
chat_model_n_gpu_layers: -1
