name: Pioneering
description: Pioneering request
type: "Pioneering 🧗"
title: "[Pioneering]: "
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the project. How popular, relevant?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or details about the project, e.g. they have a BaseURL."
    validations:
      required: false
