name: Publish Docker Image
on:
  schedule:
    # Once weekly on fridays at noon
    - cron: '00 12 * * 5'
  workflow_dispatch:

jobs:
  build-linux-image:
    name: Build Docker image for Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
    env:
      BASE_REPO: "ghcr.io/stacklok"
      CODEGATE_SERVER_IMAGE: "ghcr.io/stacklok/codegate-linux"
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3    
      - name: Compute version number
        id: version-string
        run: |
          DATE="$(date +%Y%m%d)"
          COMMIT="$(git rev-parse --short HEAD)"
          echo "tag=0.$DATE.$GITHUB_RUN_NUMBER+ref.$COMMIT" >> "$GITHUB_OUTPUT"
      - name: Login to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set container metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        id: docker-metadata
        with:
          images: ${{ env.CODEGATE_SERVER_IMAGE }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.description="This is a container for the Stacklok Codegate server"
            org.opencontainers.image.title="Stacklok Codegate Server"
            org.opencontainers.image.vendor="Stacklok Inc."
            org.opencontainers.image.version=${{ github.sha }}
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.version-string.outputs.tag }}
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v7
        with:
          github_token: ${{ github.token }}
          workflow: ".github/workflows/import_packages.yml"
          workflow_conclusion: success
          name: weaviate_data
          name_is_regexp: true
          skip_unpack: false
          if_no_artifact_found: ignore
      - name: Debug artifact extraction
        run: |
          echo "Listing extracted files:"
          ls -l ./weaviate_data        
      - name: Build image for Linux
        id: image-build-linux
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: ./Dockerfile
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            WEAVIATE_DATA_PATH=./weaviate_data/
