# Attempt to build (but not push) the Docker image on Pull Requests
name: Image build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "static/**"
      - "LICENSE"
permissions:
  contents: read
jobs:
  docker-image:
    name: Check docker image build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3
      - name: Test build on x86
        id: docker_build
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false # Only attempt to build, to verify the Dockerfile is working
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            gh_token=${{ secrets.GHP_TOKEN }}
