name: Sync vector DB

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "greet"
  sync_db:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "."

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Fetch latest successful workflow run ID and check for artifacts
      id: get-run-id
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        workflow_path=".github/workflows/import_packages.yml"
        run_id=$(gh api --paginate repos/${{ github.repository }}/actions/runs --jq ".workflow_runs[] | select(.path == \"$workflow_path\" and .conclusion == \"success\") | .workflow_id" | head -n 1)
        echo "::set-output name=run_id::$run_id"
        # Check for artifacts and set a flag
        if [[ "$run_id" != "" ]]; then
          artifacts_count=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '[.artifacts[] | select(.workflow_run.id == "$run_id")] | length > 0'
        else
          artifacts_count=0
        fi
        echo "::set-output name=has_artifacts::$([[ $artifacts_count -gt 0 ]] && echo 'true' || echo 'false')"

    - name: Download the latest artifact
      if: steps.get-run-id.outputs.has_artifacts == 'true'
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh run download ${{ steps.get-run-id.outputs.run_id }}        

    - name: Extract artifact
      if: steps.get-run-id.outputs.has_artifacts == 'true'
      run: |
        # Find the downloaded zip file (assuming only one zip file is downloaded)
        zip_file=$(ls *.zip)
        if [[ -n "$zip_file" ]]; then
          # Unzip the file in the parent directory of the current working directory
          unzip -o $zip_file -d ../
        fi
        
    - name: Run sync
      run: |
        export PYTHONPATH=$PYTHONPATH:./
        python scripts/import_packages.py
    - name: 'Upload Volume'
      uses: actions/upload-artifact@v4
      with:
        name: database_volume
        path: weaviate_data
        retention-days: 5
