name: Sync vector DB

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "greet"
  sync_db:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "."
    - name: Run sync
      run: |
        export PYTHONPATH=$PYTHONPATH:./
        python scripts/import_packages.py
    - name: 'Upload Volume'
      uses: actions/upload-artifact@v4
      with:
        name: database_volume
        path: weaviate_data
        retention-days: 5        
        
    
    
