name: Sync vector DB

on:
  workflow_dispatch:
    inputs:
      enable_artifact_download:
        description: 'Enable artifact download step'
        type: boolean
        required: false
        default: true
jobs:
  # This workflow contains a single job called "greet"
  sync_db:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "."

    - name: Download models
      run: |
        git lfs install
        git lfs pull

    - name: Download artifact
      if: ${{ github.event.inputs.enable_artifact_download == true }}    
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{ github.token }}
        workflow: ".github/workflows/import_packages.yml"
        workflow_conclusion: success
        name: weaviate_data
        name_is_regexp: true
        skip_unpack: false
        if_no_artifact_found: ignore

    - name: Run sync
      run: |
        export PYTHONPATH=$PYTHONPATH:./
        python scripts/import_packages.py
    - name: 'Upload Volume'
      uses: actions/upload-artifact@v4
      with:
        name: weaviate_data
        path: weaviate_data
        retention-days: 5
